/**
 * One voiced battle line per move id — shown in 💬 fighter quotes during the reveal.
 * Keys must exactly match MOVE_CATALOG_RAW.
 */
export const MOVE_BATTLE_PHRASES: Record<string, string> = {
  basic_strike: "No tricks—I'm taking this frame by frame!",
  guard: "Break me if you can; I'll still be standing here!",
  quick_step: "Wrong zip code—that hit's chasing smoke!",
  gale_sweep: "Ankles aren't safe when the gale lines up!",
  iron_parry: "Steel answers steel; let's hear your percussion!",
  spirit_palm: "Feel this before you see it—Spirit Palm!",
  raikiri_feint: "You looked up. That was your first mistake!",
  tempest_kick: "Ride the whirlwind or eat the floor—you pick!",
  domain_pin: "Center line's mine—you're borrowing space!",
  dojo_ultimate: "Enrollment's over—credit me with the finale!",
  ember_fist: "Leaving heat stamps where your guard pretends!",
  mist_veil: "Try aiming at footsteps and prayers!",
  root_stance: "Shove me if you dare—I'll grow roots!",
  thread_bind: "You've got strings now; let's choreograph!",
  snap_elbow: "Close-range tuition—lesson one: elbows!",
  river_roll: "Force flows—I just redirect the torrent!",
  stone_shoulder: "That impact paid my toll—now here's interest!",
  cloud_split: "Cutting through the noise—clear sky ahead!",
  needle_knee: "Rising spike—check your diaphragm!",
  echo_palm: "First tap was the question—second one's the grade!",
  drift_slide: "Lane closed—you're drifting in my lane now!",
  iron_breath: "Inhale steel, exhale calm—still here!",
  spiral_throw: "Physics called—you're volunteering for the twist!",
  pulse_check: "I felt your heartbeat stutter—that's mine!",
  shade_step: "Shadow's my co-sign—you're punching dusk!",
  thorn_push: "Every inch forward rents blood—pay up!",
  mirror_line: "Nice rhythm—hope you don't miss it when I steal it!",
  hollow_block: "Swing through ghosts—charges apply!",
  flare_turn: "Binding's cute until the spin peels you off!",
  kite_string: "Nice chase—you're on my tether now!",
  ember_guard: "Try me—this guard still burns fingerprints!",
  crane_drop: "Gravity and I drafted the same playbook!",
  serpent_whip: "Angles hiss before they strike—duck late!",
  amber_hold: "Freeze—this amber second has your name!",
  lotus_pivot: "Pivot clean—roots stay sacred!",
  thunder_rim: "Rim shot from below—wake the arena!",
  void_slip: "You swung at vacuum—I billed you air tax!",
  mountain_echo: "First hit was the probe—echo's the invoice!",
  tidebreaker: "Your wall was cute—my tide brought receipts!",
  silver_arc: "Intent cut a line—try coloring inside it!",
  heartline: "Straight shot, zero costume—face it!",
  night_ledger: "Interest compounds after dark—sign here!",
  wind_knot: "Limbs tangled mid-swing—read the breeze!",
  brazen_rush: "Space owed to me—I'm collecting with interest!",
  glass_parry: "Barely there—still sharp enough to nick pride!",
  spirit_chain: "Hits link—verdict's already stamped!",
  ember_typhoon: "Heat spirals—catch your breath if you can!",
  shadow_clock: "Every tick was mine—you're overtime!",
  aurora_kick: "Sky paid rent—my arc gets the receipt!",
  deep_current: "Dragged into my pace—welcome to the undertow!",
  iron_bloom: "Guard bloomed—petals hit like hammers!",
  luck_weave: "Probability's wearing my colors tonight!",
  phantom_tag: "Tagged—late notification included!",
  solar_rib: "Ribs lit like noon—shade won't save you!",
  monsoon_heel: "Heel rain—umbrellas banned in this bout!",
  rift_palm: "Gap opened—invoice due at contact!",
  starfall: "Meteor rent's due—pay in altitude!",
  ember_domain: "Thermostat's mine—sweat tax applies!",
  quiet_burst: "No scream—just the scoreboard talking!",
  woven_strike: "Offense and defense braided—untangle that!",
  apex_line: "Throne-bound straight shot—crowns optional!",
  eclipse_wheel: "Daylight swallowed—orbit my tempo!",
  thousand_pulse: "One blow, thousand receipts—tap in!",
  sovereign_guard: "Ruin invoiced—payment declined at my gate!",
  blood_oath_feint: "Promised chaos—delivery signature required!",
  skyhook_reversal: "Ascension reversed—landing fee extra!",
  gravity_well: "Orbit taxed—welcome to my pull!",
  mirage_fatal: "Truth mailed late—fatal postage!",
  crowned_elbow: "Royal decree: elbows speak tonight!",
  storm_ledger: "Thunder tipped—balance screams paid!",
  sanctum_wall: "Toll unpaid—sanctum says no passage!",
  razor_canvas: "Corners painted—you're framed in!",
  pulse_crown: "Heartbeat chartered—crowns tempo mine!",
  spirit_nova: "Aura invoice—paid on contact!",
  lotus_sentence: "Case closed—petals filed as evidence!",
  iron_symphony: "Guards stacking—listen for the crescendo!",
  chakrastorm: "Spiral tax—chakra weather advisory!",
  destiny_fork: "Bad branch—hope you packed excuses!",
  obsidian_slide: "Friction canceled—welcome to glide tax!",
  aurum_thread: "Gold line chartered—follow or fray!",
  void_verdict: "Judgment filed—witness optional!",
  ember_crown_kick: "Crown dips—authority kick incoming!",
  temple_breaker: "Doctrine punched—dust tuition paid!",
  harmonic_burst: "Resonance locked—you're off-key!",
  zenith_charge: "Peak stamped—apex shipping included!",
  skyforge_finisher: "Forged midair—hammer has your fax!",
  world_edge: "Endings RSVP'd—you checked in early!",
  oathbreaker_nova: "Contracts void—Nova filed the paperwork!",
  silent_cataclysm: "Quiet cataclysm—receipt screams anyway!",
  infinite_gate: "Openings multiplied—welcome to queue hell!",
  soul_tributary: "Soul toll—tributaries collect today!",
  starforge_palm: "Forged hotter than folklore—brace!",
  last_breath_arts: "Final syllabus—graded on honor!",
  absolute_line: "Debate canceled—scoreboard adjudicates!",
  heavens_ledger: "Radiance tallied—you're audited!",
  dojos_end: "Chapter clipped—dojo signs off!",
  aurora_sovereign: "Aurora salutes—you bow to light!",
  chronicle_drop: "History subpoenaed—you're footnote!",
  void_monarch: "Empty crowned—vacancy pays homage!",
  ember_genesis: "Ends begin in ember tonight—witness!",
};
